default: &default
  adapter:  postgresql
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5           } %>
  host:     <%= ENV.fetch("PGHOST")            { 'localhost' } %>
  username: <%= ENV.fetch("PGNAME")            { 'postgres'  } %>
  password: <%= ENV.fetch("PGPASSWORD")        { 'secret'    } %>
  timeout:  5000

development:
  <<: *default
  database: rails_vue_development

test:
  <<: *default
  database: rails_vue_test

production:
  <<: *default
  database: rails_vue_production
